Test
StarkovPO/Go-shop-final pull request #2
Opened 2023-05-14 06:58 UTC by StarkovPO

2023-05-18 18:02 UTC, edylcrm commented on internal/store/store.go
> +	stmt2, err := o.db.db.PrepareContext(ctx, getUserFromOrders)
db.db я бы убрал, или переименовал на более понятное

2023-05-18 18:03 UTC, edylcrm commented on internal/store/store.go
> +			_, err = stmt.ExecContext(ctx, UID, accrual)
А зачем второй раз пытаться запрос делать, если первый не удался?

2023-05-18 18:07 UTC, edylcrm commented on internal/service/go-shop-service.go
> +func (s *Service) updater(ctx context.Context, orderChan chan models.OrderFromService, baseurl string) {
А сюда динамически как-то данные в канал попадают или только пачкой? Если данные в канал буду поступать динамически то работать это будет не совсем корректно.

2023-05-18 18:18 UTC, edylcrm commented on internal/handler/handler.go
> +		if errors.As(err, &appErr) {
кажется что эти два if else можно объединить

2023-05-18 18:18 UTC, edylcrm commented on internal/handler/handler.go
> +		if errors.As(err, &appErr) {
Здесь тоже if и else можно объединить

2023-05-19 14:44 UTC, StarkovPO commented on internal/store/store.go
> +			_, err = stmt.ExecContext(ctx, UID, accrual)
Там разные запросы. Первый на создание, а второй на апдейт. Соответсвенно, если я пытаюсь создать запись, а такой UID уже есть, то я хендлю ошибку и обновляю баланс пользователя.

2023-05-19 15:07 UTC, StarkovPO commented on internal/service/go-shop-service.go
> +func (s *Service) updater(ctx context.Context, orderChan chan models.OrderFromService, baseurl string) {
Этот вопрос обсудили. Добавил таймер на 5 секунд.

2023-05-19 15:22 UTC, StarkovPO commented on internal/handler/handler.go
> +		if errors.As(err, &appErr) {
Всю обработку вынес в функцию хендлинга ошибок. Пакет appErrors

2023-05-19 15:22 UTC, StarkovPO commented on internal/handler/handler.go
> +		if errors.As(err, &appErr) {
Всю обработку вынес в функцию хендлинга ошибок. Пакет appErrors

2023-05-19 15:26 UTC, StarkovPO commented on internal/store/store.go
> +	stmt2, err := o.db.db.PrepareContext(ctx, getUserFromOrders)
Переименовал

2023-05-22 15:08 UTC, edylcrm requested changes

2023-05-22 15:08 UTC, edylcrm commented on internal/store/store_postgre.go
> +	//if _, err := db.Exec(createWithdrawForeignKey2); err != nil {
Комментарии лучше удалять. Все есть в истории гита

2023-05-22 15:08 UTC, edylcrm commented on internal/middleware/validate_jwt_token.go
> +		//headerParts := strings.Split(token, " ")
Давай удалим если не нужно

2023-05-22 15:08 UTC, edylcrm commented on internal/service/external_loyality_system.go
> +	// {"level":"error","msg":"External service responce with code: 200 and body: {\"order\":\"40534687\",\"status\":\"PROCESSED\",\"accrual\":729.98}\n","time":"2023-05-14T07:20:11Z"}
Удалить

2023-05-22 16:43 UTC, StarkovPO commented on internal/service/external_loyality_system.go
> +	// {"level":"error","msg":"External service responce with code: 200 and body: {\"order\":\"40534687\",\"status\":\"PROCESSED\",\"accrual\":729.98}\n","time":"2023-05-14T07:20:11Z"}
Готово

2023-05-22 16:43 UTC, StarkovPO commented on internal/middleware/validate_jwt_token.go
> +		//headerParts := strings.Split(token, " ")
Готово

2023-05-22 16:43 UTC, StarkovPO commented on internal/store/store_postgre.go
> +	//if _, err := db.Exec(createWithdrawForeignKey2); err != nil {
Готово

2023-05-23 18:03 UTC, edylcrm commented on internal/store/store.go
> +		if d != "pq: duplicate key value violates unique constraint \"user_id_key\"" {
А как-то по другому можно проверить эту ошибку? Выглядит не очень

2023-05-23 18:03 UTC, edylcrm commented
Нужно чтобы все чекеры проходили

2023-05-23 18:33 UTC, StarkovPO commented on internal/store/store.go
> +		if d != "pq: duplicate key value violates unique constraint \"user_id_key\"" {
Сделал по красоте))

2023-05-24 17:53 UTC, edylcrm approved these changes

2023-05-25 05:01 UTC, merged